# site variables
url:          "https://fraufraw.github.io/"
baseurl:      ""
source:       ./_src
destination:  ./_site

# meta
title: Franklin Wang
description: | # appears in search engines preview (keep it under 120 chars)
  Franklin is a student in computer science, 
  specialized Linguistics.

# jekyll collections
collections:
  - sections

# sass config
sass:
  sass_dir: _sass
  style: compressed

# static files
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      type: "sections"
    values:
      title: NewSection
      order: 10
      active: false

# jekyll plugins
plugins:
  - jekyll-minifier

# minifier settings
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

# Google Analytics measurements ID
google_analytics: G-S3FZD64MJT